In [1]:
import numpy as np

In [9]:
rand_arr1 = np.random.randn(10)
print(rand_arr1)

# accessing the 6th element from the array
print(rand_arr1[6])

# accessing multiple entries from the array
print(rand_arr1[4:9])

print('index of values to access : ', np.arange(3,10,3))
print(rand_arr1[np.arange(3,10,3)])

[-0.78729536 -0.0957528  -0.82843886 -0.10980505  1.1442325   1.18988507
  1.24310005 -1.19107079  0.76388133  0.01209937]
1.2431000466635231
[ 1.1442325   1.18988507  1.24310005 -1.19107079  0.76388133]
index of values to access :  [3 6 9]
[-0.10980505  1.24310005  0.01209937]


In [10]:
print(rand_arr1)

[-0.78729536 -0.0957528  -0.82843886 -0.10980505  1.1442325   1.18988507
  1.24310005 -1.19107079  0.76388133  0.01209937]


In [23]:
rand_arr1 > 0

array([False, False, False, False,  True,  True,  True, False,  True,
        True])

In [22]:
# accessing arrays using logical operators

print('values lesser than 0 : ', rand_arr1[rand_arr1 < 0])
print('values greater than 0 : ', rand_arr1[rand_arr1 > 0])

values lesser than 0 :  [-0.78729536 -0.0957528  -0.82843886 -0.10980505 -1.19107079]
values greater than 0 :  [1.1442325  1.18988507 1.24310005 0.76388133 0.01209937]


In [18]:
# accessing the entries of a matrix
rand_mat1 = np.random.randn(5,5)
print(rand_mat1)


[[-0.10942346  0.80179678 -0.23724526 -2.86368683  0.8685284 ]
 [-0.21864473 -0.35747761  0.56125222 -1.01467643 -0.20586858]
 [ 1.3695902  -1.57881518  1.08100221  0.1233306   0.64519728]
 [-0.90990531  0.37260292  0.23733193 -0.05081694 -0.31672821]
 [-0.78901794  0.27984531  1.06146086 -1.3496279   0.35408027]]


In [19]:
rand_mat1[1]

array([-0.21864473, -0.35747761,  0.56125222, -1.01467643, -0.20586858])

In [20]:
# accessing 3rd element in 2nd row

print(rand_mat1[1, 2])

0.5612522197796288


In [24]:
# accessing 3rd element in 2nd row

print(rand_mat1[1][2])

0.5612522197796288


In [26]:
# accessing 1st row -> 2nd column and 2nd row -> 3rd column

print(rand_mat1[0:2, 1:3])

[[ 0.80179678 -0.23724526]
 [-0.35747761  0.56125222]]


In [27]:
# accessing matrices using logical operations

print(rand_mat1)

[[-0.10942346  0.80179678 -0.23724526 -2.86368683  0.8685284 ]
 [-0.21864473 -0.35747761  0.56125222 -1.01467643 -0.20586858]
 [ 1.3695902  -1.57881518  1.08100221  0.1233306   0.64519728]
 [-0.90990531  0.37260292  0.23733193 -0.05081694 -0.31672821]
 [-0.78901794  0.27984531  1.06146086 -1.3496279   0.35408027]]


In [28]:
rand_mat1 > 0

array([[False,  True, False, False,  True],
       [False, False,  True, False, False],
       [ True, False,  True,  True,  True],
       [False,  True,  True, False, False],
       [False,  True,  True, False,  True]])

In [30]:

print('values lesser than 0 : \n', rand_mat1[rand_mat1 < 0])
print('values greater than 0 : \n', rand_mat1[rand_mat1 > 0])

values lesser than 0 : 
 [-0.10942346 -0.23724526 -2.86368683 -0.21864473 -0.35747761 -1.01467643
 -0.20586858 -1.57881518 -0.90990531 -0.05081694 -0.31672821 -0.78901794
 -1.3496279 ]
values greater than 0 : 
 [0.80179678 0.8685284  0.56125222 1.3695902  1.08100221 0.1233306
 0.64519728 0.37260292 0.23733193 0.27984531 1.06146086 0.35408027]


In [31]:
# modifying the entries of an array

print(rand_arr1)

[-0.78729536 -0.0957528  -0.82843886 -0.10980505  1.1442325   1.18988507
  1.24310005 -1.19107079  0.76388133  0.01209937]


In [33]:
# let's change some values in an array
# changing the values of index value of 3 to 5 and index value 4 to 5

rand_arr1[3:5] = 5
print(rand_arr1)

[-0.78729536 -0.0957528  -0.82843886  5.          5.          1.18988507
  1.24310005 -1.19107079  0.76388133  0.01209937]


In [34]:
# changing the values of index value of 0 and 1 to 2 and 3 respectively

rand_arr1[0:2] = [2,3]
print(rand_arr1)

[ 2.          3.         -0.82843886  5.          5.          1.18988507
  1.24310005 -1.19107079  0.76388133  0.01209937]


In [35]:
# modify using logical reference

rand_arr1[rand_arr1 > 0] = 65

In [36]:
print(rand_arr1)

[65.         65.         -0.82843886 65.         65.         65.
 65.         -1.19107079 65.         65.        ]
