In [13]:
import numpy as np

In [14]:
"""
        - start   : default start = 0
        - stop    : end of interval range
        - step    : step size of interval. default step = 1
"""
arr1 = np.arange(start=0, stop=10)  # 10 will be excluded from the output
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
arr2 = np.arange(0,10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
# add a step of 2
arr3 = np.arange(start=0, stop=10, step=2)  # 10 will be excluded from the output
print(arr3)

[0 2 4 6 8]


In [17]:
""" 
    Use np.linespace() function - returns numbes which are evenly distributed w.r.t interval
        - start   : default start = 0
        - stop    : end of interval range
        - step    : Number of samples to generate. default step = 50
        step size = (stop - start) / (total elements - 1)  = (5-0)/49 = 0.10204082
"""
matrix2 = np.linspace(0,5)
matrix2

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [18]:
# generating 10 evenly spaces values between 10 and 20

In [19]:
matrix3 = np.linspace(10,20,10)
matrix3

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [20]:
matrix4 = np.linspace(10,20,11)
matrix4

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [21]:
"""
    use np.zeros() -> returns a matrix filled with zeros of given shape
        - shape : number of rows and columns in the output matrix
        - dtype : data type of the elements in the matrix, default value is set to float
"""
matrix5 = np.zeros([3,5])
matrix5

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
"""
    use np.ones() -> returns a matrix filled with 1's of given shape
        - shape : number of rows and columns in the output matrix
        - dtype : data type of the elements in the matrix, default value is set to float
"""
matrix6 = np.ones([3,5])
matrix6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
"""
    use np.eye() -> returns a matrix filled with 1's on diagonals and 0's elsewhere of the given shape
        - shape : number of rows and columns in the output matrix
        - dtype : data type of the elements in the matrix, default value is set to float
"""
matrix7 = np.eye(5)
matrix7

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])