In [1]:
import numpy as np

In [2]:
arr_str = ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']

# convert the list to NumPy array
np_arr_str = np.array(arr_str)
print("arr_str = ", arr_str)
print("np_arr_str = ", np_arr_str)

arr_str =  ['Mercedes', 'BMW', 'Audi', 'Ferrari', 'Tesla']
np_arr_str =  ['Mercedes' 'BMW' 'Audi' 'Ferrari' 'Tesla']


In [3]:
arr_num = [5, 4, 7, 6, 3]

# convert the list to NumPy array
np_arr_num = np.array(arr_num)
print("arr_num = ", arr_num)
print("np_arr_num = ", np_arr_num)

arr_num =  [5, 4, 7, 6, 3]
np_arr_num =  [5 4 7 6 3]


In [4]:
# data type of list
print("data type of arr_str = ", type(arr_str))
print("data type of arr_num = ", type(arr_num))

 # data type (after conversion) list to array
print("data type of np_arr_str = ", type(np_arr_str))
print("data type of np_arr_num = ", type(np_arr_num))

data type of arr_str =  <class 'list'>
data type of arr_num =  <class 'list'>
data type of np_arr_str =  <class 'numpy.ndarray'>
data type of np_arr_num =  <class 'numpy.ndarray'>


In [5]:
matrix = np.array([[1,2,1],[4,5,9],[1,8,9]])
print(matrix)
print("data type of matrix = ", type(matrix))

[[1 2 1]
 [4 5 9]
 [1 8 9]]
data type of matrix =  <class 'numpy.ndarray'>
