In [5]:
import numpy as np

In [8]:
# arithmetic on list
l1=[1,2,3]
l2=[4,5,6]
print(l1 + l2)

[1, 2, 3, 4, 5, 6]


In [9]:
# we can +-*/ arrays together

arr1 = np.arange(1,6)
print('arr1 = ', arr1)

arr2 = np.arange(3,8)
print('arr2 = ', arr2)

arr1 =  [1 2 3 4 5]
arr2 =  [3 4 5 6 7]


In [10]:
print('addition = ', arr1 + arr2)
print('subtraction = ', arr1 - arr2)
print('multiplication = ', arr1 * arr2)
print('division = ', arr1 / arr2)
print('inverse = ', 1/arr1)
print('powers = ', arr1 ** arr2)

addition =  [ 4  6  8 10 12]
subtraction =  [-2 -2 -2 -2 -2]
multiplication =  [ 3  8 15 24 35]
division =  [0.33333333 0.5        0.6        0.66666667 0.71428571]
inverse =  [1.         0.5        0.33333333 0.25       0.2       ]
powers =  [    1    16   243  4096 78125]


In [11]:
# operations on matrices

arr3 = np.arange(1,10).reshape(3,3)
print(arr3)

arr4 = np.eye(3)
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
print('addition = \n', arr3 + arr4)
print('subtraction = \n', arr3 - arr4)
print('multiplication = \n', arr3 * arr4)
print('division = \n', arr3 / arr4)


addition = 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
subtraction = 
 [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
multiplication = 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
division = 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


/var/folders/d8/grpm6rlx467dk8kfz2zlcfcc0000gn/T/ipykernel_32825/4106955805.py:4: RuntimeWarning: divide by zero encountered in divide
  print('division = \n', arr3 / arr4)


In [15]:
# Linear algebra matrix multiplication

matrix9 = np.arange(1,10).reshape(3,3)
print('first matrix = \n', matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print('second matrix = \n', matrix10)

# dot product
print('Multiplication = \n', matrix9 @ matrix10)

first matrix = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
second matrix = 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Multiplication = 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [20]:
# transpose a matrix

print(matrix9)
np.transpose(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [21]:
# another way of making transpose
matrix9.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
# max and min in a matrix

print(matrix9)
print('min value = ', np.min(matrix9))
print('max value = ', np.max(matrix9))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
min value =  1
max value =  9


In [24]:
# generate random sample (including 0 but, excluding 1)
np.random.rand(5)

array([0.53417317, 0.88255761, 0.45138466, 0.41817082, 0.30737541])

In [27]:
print(np.random.rand(5,5))

[[0.9542369  0.46301251 0.2799839  0.76413805 0.08710705]
 [0.74730584 0.42485762 0.23756009 0.71669952 0.84803924]
 [0.69131475 0.41343147 0.8333778  0.0067329  0.31528076]
 [0.45763255 0.91368569 0.82107483 0.53077826 0.92440234]
 [0.639859   0.74077775 0.25002335 0.34000008 0.45864107]]


In [28]:
# randn function (standard normal distribution - mean as 0 and standard deviation as 1)
print(np.random.randn(5,5))

[[ 0.47080009 -0.82563502 -0.07415588  1.15833972  0.77433838]
 [ 0.07654844  0.79379957 -1.23395936 -0.48457873 -0.5939    ]
 [ 0.12198305  0.63728637 -0.19205036 -2.77956039 -0.77801856]
 [-1.09236222 -0.39328865  1.61905235  0.52451241 -0.87554727]
 [-0.9137273  -0.7112049  -1.74230944 -0.8888108  -0.45296594]]


In [29]:
print('Mean : ', np.mean(np.random.rand(5,5)))
print('Standard Deviation : ', np.std(np.random.rand(5,5)))

Mean :  0.4357951196802457
Standard Deviation :  0.28486519779903946
