In [1]:
import numpy as np

In [2]:
# arithmetic on list
l1=[1,2,3]
l2=[4,5,6]
print(l1 + l2)

[1, 2, 3, 4, 5, 6]


In [3]:
# we can +-*/ arrays together

arr1 = np.arange(1,6)
print('arr1 = ', arr1)

arr2 = np.arange(3,8)
print('arr2 = ', arr2)

arr1 =  [1 2 3 4 5]
arr2 =  [3 4 5 6 7]


In [4]:
print('addition = ', arr1 + arr2)
print('subtraction = ', arr1 - arr2)
print('multiplication = ', arr1 * arr2)
print('division = ', arr1 / arr2)
print('inverse = ', 1/arr1)
print('powers = ', arr1 ** arr2)

addition =  [ 4  6  8 10 12]
subtraction =  [-2 -2 -2 -2 -2]
multiplication =  [ 3  8 15 24 35]
division =  [0.33333333 0.5        0.6        0.66666667 0.71428571]
inverse =  [1.         0.5        0.33333333 0.25       0.2       ]
powers =  [    1    16   243  4096 78125]


In [5]:
# operations on matrices

arr3 = np.arange(1,10).reshape(3,3)
print(arr3)

arr4 = np.eye(3)
print(arr4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
print('addition = \n', arr3 + arr4)
print('subtraction = \n', arr3 - arr4)
print('multiplication = \n', arr3 * arr4)
print('division = \n', arr3 / arr4)


addition = 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
subtraction = 
 [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
multiplication = 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
division = 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


/var/folders/d8/grpm6rlx467dk8kfz2zlcfcc0000gn/T/ipykernel_87308/4106955805.py:4: RuntimeWarning: divide by zero encountered in divide
  print('division = \n', arr3 / arr4)


In [7]:
# Linear algebra matrix multiplication

matrix9 = np.arange(1,10).reshape(3,3)
print('first matrix = \n', matrix9)

matrix10 = np.arange(11,20).reshape(3,3)
print('second matrix = \n', matrix10)

# dot product
print('Multiplication = \n', matrix9 @ matrix10)

first matrix = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
second matrix = 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
Multiplication = 
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [8]:
# transpose a matrix

print(matrix9)
np.transpose(matrix9)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [9]:
# another way of making transpose
matrix9.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
# max and min in a matrix

print(matrix9)
print('min value = ', np.min(matrix9))
print('max value = ', np.max(matrix9))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
min value =  1
max value =  9


In [11]:
# generate random sample (including 0 but, excluding 1)
np.random.rand(5)

array([0.16895293, 0.07987029, 0.03888935, 0.32049794, 0.00736605])

In [12]:
print(np.random.rand(5,5))

[[0.62456722 0.86388777 0.70829143 0.02644402 0.38705321]
 [0.16097964 0.8806206  0.7716792  0.22432435 0.7964755 ]
 [0.20522277 0.1196421  0.12687718 0.10793812 0.1501377 ]
 [0.88045646 0.24722209 0.30121192 0.17008715 0.44218101]
 [0.59469256 0.9185095  0.75940491 0.33420985 0.06671947]]


In [13]:
# randn function (standard normal distribution - mean as 0 and standard deviation as 1)
print(np.random.randn(5,5))

[[ 1.50507687  0.23778427  0.4010948   2.39476837  0.64737449]
 [-0.73612344 -0.88181661  1.97110395  0.61184381 -1.01080129]
 [-0.05313415  0.31650829  0.04288506  2.09091341  0.86433011]
 [-2.22932723  0.2654633  -0.32753995  1.0755454  -0.03057358]
 [ 0.67015411  0.3088761   0.31645913  1.32633117 -0.89818732]]


In [14]:
print('Mean : ', np.mean(np.random.rand(5,5)))
print('Standard Deviation : ', np.std(np.random.rand(5,5)))

Mean :  0.4244048045194907
Standard Deviation :  0.3182500027497282


In [15]:
# generating random values in an array
rand_mat1 = np.random.randint(1,5,10)
print(rand_mat1)

[3 2 4 2 3 2 1 3 4 3]


In [16]:
# generating random values in a matrix
rand_mat2 = np.random.randint(1,10, [5,5])
print(rand_mat2)

[[1 1 3 8 1]
 [9 5 7 4 7]
 [3 2 7 2 4]
 [7 8 9 2 9]
 [2 8 4 5 7]]
