In [2]:
import numpy as np

In [3]:
# create random matrices

randint_matrix1 = np.random.randint(1,10,10).reshape(2,5)
print(randint_matrix1)

print('')

randint_matrix2 = np.random.randint(10,20,10).reshape(2,5)
print(randint_matrix2)


[[9 2 9 6 9]
 [6 5 3 6 5]]

[[16 13 19 11 19]
 [19 12 16 16 12]]


In [7]:
# use np.save() function

np.save('/Users/sandeepdash/Sandeep/Practice/python_practice/GreatLearning_AIML/GL-AIML/02_NumPy_Pandas/saved_file', randint_matrix1)

In [8]:
# use np.savez

np.savez('/Users/sandeepdash/Sandeep/Practice/python_practice/GreatLearning_AIML/GL-AIML/02_NumPy_Pandas/multiple_file', randint_matrix1 = randint_matrix1, randint_matrix2 = randint_matrix2)

In [9]:
# load .npy file

loaded_arr = np.load('/Users/sandeepdash/Sandeep/Practice/python_practice/GreatLearning_AIML/GL-AIML/02_NumPy_Pandas/saved_file.npy')
loaded_multi = np.load('/Users/sandeepdash/Sandeep/Practice/python_practice/GreatLearning_AIML/GL-AIML/02_NumPy_Pandas/multiple_file.npz')

print(loaded_arr)
print('')
print(loaded_multi)


[[9 2 9 6 9]
 [6 5 3 6 5]]

NpzFile '/Users/sandeepdash/Sandeep/Practice/python_practice/GreatLearning_AIML/GL-AIML/02_NumPy_Pandas/multiple_file.npz' with keys: randint_matrix1, randint_matrix2


In [10]:
print('1st matrix: \n', loaded_multi['randint_matrix1'])
print('2nd matrix: \n', loaded_multi['randint_matrix2'])

new_matrix = loaded_multi['randint_matrix1']
print('new matrix: \n', new_matrix)

1st matrix: 
 [[9 2 9 6 9]
 [6 5 3 6 5]]
2nd matrix: 
 [[16 13 19 11 19]
 [19 12 16 16 12]]
new matrix: 
 [[9 2 9 6 9]
 [6 5 3 6 5]]


In [11]:
# we can also save/load text files... but only single variables

np.savetxt('/Users/sandeepdash/Sandeep/Practice/python_practice/GreatLearning_AIML/GL-AIML/02_NumPy_Pandas/text_file_name.txt', randint_matrix1, delimiter=",")
rand_mat_txt = np.loadtxt('/Users/sandeepdash/Sandeep/Practice/python_practice/GreatLearning_AIML/GL-AIML/02_NumPy_Pandas/text_file_name.txt', delimiter=",")

print(randint_matrix1)
print('')
print(rand_mat_txt)

[[9 2 9 6 9]
 [6 5 3 6 5]]

[[9. 2. 9. 6. 9.]
 [6. 5. 3. 6. 5.]]
