In [1]:
import numpy as np

In [7]:
rand_mat1 = np.random.randint(1,10, [5,5])
print(rand_mat1)

[[2 9 5 4 1]
 [9 3 7 6 8]
 [5 1 1 4 4]
 [5 7 7 6 6]
 [6 9 4 1 8]]


In [8]:
# modifying the entries of a matrix

print('matrix before modification: \n', rand_mat1)

rand_mat1[1:3, 3:5] = 0
print('matrix after modification: \n', rand_mat1)

matrix before modification: 
 [[2 9 5 4 1]
 [9 3 7 6 8]
 [5 1 1 4 4]
 [5 7 7 6 6]
 [6 9 4 1 8]]
matrix after modification: 
 [[2 9 5 4 1]
 [9 3 7 0 0]
 [5 1 1 0 0]
 [5 7 7 6 6]
 [6 9 4 1 8]]


In [9]:
# extracting 1st 2 rows and 1st 3 columns from a matrix

sub_mat = rand_mat1[0:2, 0:3]
print(sub_mat)

[[2 9 5]
 [9 3 7]]


In [10]:
# chaneing all the values of the extracted matrix to 3

sub_mat[:] = 3
print(sub_mat)

[[3 3 3]
 [3 3 3]]


In [11]:
# the original matrix got changed with the values

rand_mat1

array([[3, 3, 3, 4, 1],
       [3, 3, 3, 0, 0],
       [5, 1, 1, 0, 0],
       [5, 7, 7, 6, 6],
       [6, 9, 4, 1, 8]])

In [15]:
# to prevent this change, we need to use the .copy() method

rand_mat2 = np.random.randn(5,5)
print(rand_mat2)

sub_mat2 = rand_mat2[0:2, 0:3].copy()
sub_mat2[:] = 3
print(sub_mat2)
print(rand_mat2)

[[-0.17324995  0.530079   -0.17404229  0.40677747  1.77953375]
 [ 0.82548137 -1.7425778   0.41255523  0.51700271 -1.78679075]
 [-1.67329881 -0.4865764   1.58878832 -0.1220412   1.00594529]
 [-1.00528286  1.92947637  1.60179138 -1.93515705 -0.44855692]
 [-0.350012    0.56208982 -0.51607576 -0.68591718  0.13415438]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[-0.17324995  0.530079   -0.17404229  0.40677747  1.77953375]
 [ 0.82548137 -1.7425778   0.41255523  0.51700271 -1.78679075]
 [-1.67329881 -0.4865764   1.58878832 -0.1220412   1.00594529]
 [-1.00528286  1.92947637  1.60179138 -1.93515705 -0.44855692]
 [-0.350012    0.56208982 -0.51607576 -0.68591718  0.13415438]]


In [14]:
rand_mat2 = np.random.randint(1,10, [5,5])
print(rand_mat2)

sub_mat2 = rand_mat2[0:2, 0:3].copy()
sub_mat2[:] = 3
print(sub_mat2)
print(rand_mat2)

[[2 4 3 7 3]
 [4 8 4 1 3]
 [3 2 1 4 8]
 [6 5 2 8 5]
 [4 1 7 5 7]]
[[3 3 3]
 [3 3 3]]
[[2 4 3 7 3]
 [4 8 4 1 3]
 [3 2 1 4 8]
 [6 5 2 8 5]
 [4 1 7 5 7]]
