In [5]:
import numpy as np

In [2]:
# definling an array with values 0 to 9
arr1 = np.arange(0, 10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
"""
    convert 1-dimension array to matrix. This can be done using np.reshape() function
    By reshaping an array we can add or remove dimensions or change number of the elements in each dimension
    Syntax: 
        array.reshape(shape)
    shape = a tuple given as input. The values in the tuple will be the new shape of the array
"""
# reshaping the array arr1 to a 2 X 5 matrix
arr1_reshaped = arr1.reshape((2,5))
arr1_reshaped

# reshaping to 2 X 6 is not possible, as 12 elements will be needed to fit into 2 X 6.

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
"""
    NumPy can also perform a  large number of different mathematical operations.
    1. Trigonometric functions
    2. Exponents and Logarithmic functions
    3. Functions for arithmetic operations between arrays and metrices
"""

# 1. Trigonometric functions
print('Sine function = ', np.sin(90))
print('Cosine function = ', np.cos(90))
print('Tan function = ', np.tan(90))

print('Sine function pi/2 = ', np.sin(np.pi/2))
print('Cosine function pi/2 = ', np.cos(np.pi))
print('Tan function pi/2 = ', np.tan(1))

Sine function =  0.8939966636005579
Cosine function =  -0.4480736161291702
Tan function =  -1.995200412208242
Sine function pi/2 =  1.0
Cosine function pi/2 =  -1.0
Tan function pi/2 =  1.557407724654902


In [12]:
print('Sine function = ', np.sin(arr1))
print('Cosine function = ', np.cos(arr1))
print('Tan function = ', np.tan(arr1))

Sine function =  [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
Cosine function =  [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
Tan function =  [ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566]


In [7]:
# exponents
print(np.exp(2))
print(np.exp2(2))

arr2 = np.array([2,4,6])
np.exp(arr2)

7.38905609893065
4.0


array([  7.3890561 ,  54.59815003, 403.42879349])

In [8]:
# logarithms
print(np.log(arr2))
print(np.log10(arr2))

[0.69314718 1.38629436 1.79175947]
[0.30103    0.60205999 0.77815125]


In [9]:
np.log10(1000)

3.0